### ISSUE TITLE
Mac OS - onehack window is not displayed.

### ISSUE THREAD

**Issue by ghost** [ahmedayman4a/1Hack#3] opened 2020-04-08 11:54 UTC
1. Open the application in mac
2. Under File Menu - Click Close window.
3. Now there's no way to reopen the window.
4. Even after quitting the application and reopening, the Application window is not displayed.

**Comment by ahmedayman4a** [comment] 2020-04-08 12:00
Is it not in the menu bar?

**Comment by ghost** [comment] 2020-04-08 12:30
Attached recording!

![1hack](https://user-images.githubusercontent.com/4454108/78784321-c4c3bd00-79c2-11ea-88fb-5ac11f21265c.gif)

Point no 4: Quitting and reopening resolves the issue. 
Ignore Point 4

**Comment by ahmedayman4a** [comment] 2020-04-08 12:57
So from what I understand: 
Expected result : 
* When you close the application 1Hack icon should appear in the [Status menus](https://support.apple.com/en-eg/guide/mac-help/mchlp1446/mac) 
* There shouldn't even be a menu bar like this : [MacOS Example](https://gm1.ggpht.com/dGfAvEkqG6HB9T7wz6UcO27Lq8nGNE2zrpbm2Zd8gqbwMZqw4DryB7N6WN-cqtTxm8AgUtj9ILss1nZYXBC8MDRUjUFgzGREw7yi2hN2FLonGADtpiP4eB-sOlDFcwRwLi4mUaNtsDC1hlq1YPfYjHhz-tmlNQ9yQHVRX5xjmlIqhrCj-n_a-3UHPVg1sVY4wdgHq_GoTMxyyQkiQ2lfChEUmE4FivWQbizi2_8H769atrFIDbKagjqS7y633lw1eyfGSlFkmJGSXE246fita6AtuKc-ZxfcbKUvlS6keae2qVzkUeLZyRFIGuzpbDnjjAoxxmmE98DZxggAQuZYv38qCRUa-KzrHpFtvtl-kn-Eq8RJr3uoaXeARrkZ5fwg-RZYjZKBtDn70I3IB5RC0tRhwUXYe9FmbhSSV1EJ176b8abmfci8oPG72Pr0qqLAb2QUBj-VOcv1wvNUZ4uShPjRIz_W1yjvK0h1WxftS34NCH4Vo6s20Ed19VVIqO0Vt50DEkZrNRSNE7IAzZjQcVW7ySBvYEg0mQqHUVASgyhBMLfWQQTuJOJ7iu2jevbKhhh2o6DiLqWaBUvl5FIVNXXFZcQx6qZEl9SLqPFdBuxD4I-lFhDxt0oOAilycYG8Ke-proyAf8mtkGY5ialooDcmgL0WFxuFdZLbX4UtP7nm1lavRCUD9rnxlNBNWsTf4EZ1sWpW1GWugdsg1-eMH7TXeTbTSj5D_C0f3EPDZ_Y29l63c-zc0KK-_947GEE2Q67oKSs=s0-l75-ft-l75-ft)

Actual Result : 
* When you close the application you can't reopen it unless you completely quit the application
* There is a menu bar with some options disabled

#### Are all the points correct?
If yes then I think apple doesn't give the permission for apps that aren't installed to appear in the status menu unlike Windows as the app can appear in Tray

#### Do you have any settings you have changed in the past on your mac that might cause the above issues. For example : did you disable status menu or forced applications to have menu bars?
#### Note: I am just speculating.  I have never used or even touched a Mac before.

**Comment by ayush5harma** [comment] 2020-04-08 13:32
> * Open the application in mac
> * Under File Menu - Click Close window.
> * Now there's no way to reopen the window.
> * Even after quitting the application and reopening, the Application window is not displayed.



> So from what I understand:
> Expected result :
> 
> * When you close the application 1Hack icon should appear in the [Status menus](https://support.apple.com/en-eg/guide/mac-help/mchlp1446/mac)
> * There shouldn't even be a menu bar like this : [MacOS Example](https://gm1.ggpht.com/dGfAvEkqG6HB9T7wz6UcO27Lq8nGNE2zrpbm2Zd8gqbwMZqw4DryB7N6WN-cqtTxm8AgUtj9ILss1nZYXBC8MDRUjUFgzGREw7yi2hN2FLonGADtpiP4eB-sOlDFcwRwLi4mUaNtsDC1hlq1YPfYjHhz-tmlNQ9yQHVRX5xjmlIqhrCj-n_a-3UHPVg1sVY4wdgHq_GoTMxyyQkiQ2lfChEUmE4FivWQbizi2_8H769atrFIDbKagjqS7y633lw1eyfGSlFkmJGSXE246fita6AtuKc-ZxfcbKUvlS6keae2qVzkUeLZyRFIGuzpbDnjjAoxxmmE98DZxggAQuZYv38qCRUa-KzrHpFtvtl-kn-Eq8RJr3uoaXeARrkZ5fwg-RZYjZKBtDn70I3IB5RC0tRhwUXYe9FmbhSSV1EJ176b8abmfci8oPG72Pr0qqLAb2QUBj-VOcv1wvNUZ4uShPjRIz_W1yjvK0h1WxftS34NCH4Vo6s20Ed19VVIqO0Vt50DEkZrNRSNE7IAzZjQcVW7ySBvYEg0mQqHUVASgyhBMLfWQQTuJOJ7iu2jevbKhhh2o6DiLqWaBUvl5FIVNXXFZcQx6qZEl9SLqPFdBuxD4I-lFhDxt0oOAilycYG8Ke-proyAf8mtkGY5ialooDcmgL0WFxuFdZLbX4UtP7nm1lavRCUD9rnxlNBNWsTf4EZ1sWpW1GWugdsg1-eMH7TXeTbTSj5D_C0f3EPDZ_Y29l63c-zc0KK-_947GEE2Q67oKSs=s0-l75-ft-l75-ft)
> 
> Actual Result :
> 
> * When you close the application you can't reopen it unless you completely quit the application
> * There is a menu bar with some options disabled
> 
> #### Are all the points correct?
> If yes then I think apple doesn't give the permission for apps that aren't installed to appear in the status menu unlike Windows as the app can appear in Tray
> 
> #### Do you have any settings you have changed in the past on your mac that might cause the above issues. For example : did you disable status menu or forced applications to have menu bars?
> #### Note: I am just speculating. I have never used or even touched a Mac before.

The app launches as minimised status menu item in the menu bar and hence if you close it from file menu or close button that will only removes it from the overview.The app can be reopened from menu bar but not from the dock as clicking on the dock only  initiate the app which is already minimised in the status menu.
This is an **app launch behaviour** and **not a bug**.

**Comment by ghost** [comment] 2020-04-08 13:53
If the above issue is not a bug, then we should quit/close the entire app when user clicks "X" icon or "Close Window" in the file menu.

In the current behaviour, there's no way for an user to reopen the dialog unless he quits and reopens the app.

**Comment by ghost** [comment] 2020-04-08 13:54
> So from what I understand:
> Expected result :
> 
> * When you close the application 1Hack icon should appear in the [Status menus](https://support.apple.com/en-eg/guide/mac-help/mchlp1446/mac)
> * There shouldn't even be a menu bar like this : [MacOS Example](https://gm1.ggpht.com/dGfAvEkqG6HB9T7wz6UcO27Lq8nGNE2zrpbm2Zd8gqbwMZqw4DryB7N6WN-cqtTxm8AgUtj9ILss1nZYXBC8MDRUjUFgzGREw7yi2hN2FLonGADtpiP4eB-sOlDFcwRwLi4mUaNtsDC1hlq1YPfYjHhz-tmlNQ9yQHVRX5xjmlIqhrCj-n_a-3UHPVg1sVY4wdgHq_GoTMxyyQkiQ2lfChEUmE4FivWQbizi2_8H769atrFIDbKagjqS7y633lw1eyfGSlFkmJGSXE246fita6AtuKc-ZxfcbKUvlS6keae2qVzkUeLZyRFIGuzpbDnjjAoxxmmE98DZxggAQuZYv38qCRUa-KzrHpFtvtl-kn-Eq8RJr3uoaXeARrkZ5fwg-RZYjZKBtDn70I3IB5RC0tRhwUXYe9FmbhSSV1EJ176b8abmfci8oPG72Pr0qqLAb2QUBj-VOcv1wvNUZ4uShPjRIz_W1yjvK0h1WxftS34NCH4Vo6s20Ed19VVIqO0Vt50DEkZrNRSNE7IAzZjQcVW7ySBvYEg0mQqHUVASgyhBMLfWQQTuJOJ7iu2jevbKhhh2o6DiLqWaBUvl5FIVNXXFZcQx6qZEl9SLqPFdBuxD4I-lFhDxt0oOAilycYG8Ke-proyAf8mtkGY5ialooDcmgL0WFxuFdZLbX4UtP7nm1lavRCUD9rnxlNBNWsTf4EZ1sWpW1GWugdsg1-eMH7TXeTbTSj5D_C0f3EPDZ_Y29l63c-zc0KK-_947GEE2Q67oKSs=s0-l75-ft-l75-ft)
> 
> Actual Result :
> 
> * When you close the application you can't reopen it unless you completely quit the application
> * There is a menu bar with some options disabled
> 
> #### Are all the points correct?
> If yes then I think apple doesn't give the permission for apps that aren't installed to appear in the status menu unlike Windows as the app can appear in Tray
> 
> #### Do you have any settings you have changed in the past on your mac that might cause the above issues. For example : did you disable status menu or forced applications to have menu bars?
> #### Note: I am just speculating. I have never used or even touched a Mac before.

No i've disabled any menu. I just close the dialog window using close button or cmd + w

**Comment by ghost** [comment] 2020-04-08 13:56
**Suggestion:**

You can introduce a new option in the file menu to open the browser dialog again.

**Comment by ayush5harma** [comment] 2020-04-08 14:07
> > So from what I understand:
> > Expected result :
> > 
> > * When you close the application 1Hack icon should appear in the [Status menus](https://support.apple.com/en-eg/guide/mac-help/mchlp1446/mac)
> > * There shouldn't even be a menu bar like this : [MacOS Example](https://gm1.ggpht.com/dGfAvEkqG6HB9T7wz6UcO27Lq8nGNE2zrpbm2Zd8gqbwMZqw4DryB7N6WN-cqtTxm8AgUtj9ILss1nZYXBC8MDRUjUFgzGREw7yi2hN2FLonGADtpiP4eB-sOlDFcwRwLi4mUaNtsDC1hlq1YPfYjHhz-tmlNQ9yQHVRX5xjmlIqhrCj-n_a-3UHPVg1sVY4wdgHq_GoTMxyyQkiQ2lfChEUmE4FivWQbizi2_8H769atrFIDbKagjqS7y633lw1eyfGSlFkmJGSXE246fita6AtuKc-ZxfcbKUvlS6keae2qVzkUeLZyRFIGuzpbDnjjAoxxmmE98DZxggAQuZYv38qCRUa-KzrHpFtvtl-kn-Eq8RJr3uoaXeARrkZ5fwg-RZYjZKBtDn70I3IB5RC0tRhwUXYe9FmbhSSV1EJ176b8abmfci8oPG72Pr0qqLAb2QUBj-VOcv1wvNUZ4uShPjRIz_W1yjvK0h1WxftS34NCH4Vo6s20Ed19VVIqO0Vt50DEkZrNRSNE7IAzZjQcVW7ySBvYEg0mQqHUVASgyhBMLfWQQTuJOJ7iu2jevbKhhh2o6DiLqWaBUvl5FIVNXXFZcQx6qZEl9SLqPFdBuxD4I-lFhDxt0oOAilycYG8Ke-proyAf8mtkGY5ialooDcmgL0WFxuFdZLbX4UtP7nm1lavRCUD9rnxlNBNWsTf4EZ1sWpW1GWugdsg1-eMH7TXeTbTSj5D_C0f3EPDZ_Y29l63c-zc0KK-_947GEE2Q67oKSs=s0-l75-ft-l75-ft)
> > 
> > Actual Result :
> > 
> > * When you close the application you can't reopen it unless you completely quit the application
> > * There is a menu bar with some options disabled
> > 
> > #### Are all the points correct?
> > If yes then I think apple doesn't give the permission for apps that aren't installed to appear in the status menu unlike Windows as the app can appear in Tray
> > #### Do you have any settings you have changed in the past on your mac that might cause the above issues. For example : did you disable status menu or forced applications to have menu bars?
> > #### Note: I am just speculating. I have never used or even touched a Mac before.
> 
> No i've disabled any menu. I just close the dialog window using close button or cmd + w

you don't see any icon in the menu bar for the app ?

**Comment by ghost** [comment] 2020-04-08 14:24
Check the GIF posted above. Under File Menu, there's only "Close Window" option.

**Comment by ahmedayman4a** [comment] 2020-04-08 14:46
@rcsekar  Can you post a gif showing the whole screen and you opening and closing 1Hack app(Don't crop any part of the screen out).
Thank you.

**Comment by ayush5harma** [comment] 2020-04-08 14:47
> Check the GIF posted above. Under File Menu, there's only "Close Window" option.

![Screenshot 2020-04-08 at 8 14 51 PM](https://user-images.githubusercontent.com/47772616/78797786-d1054580-79d5-11ea-95c6-94a0c5999144.png)
This icon on the top right is what I was talking about.

**Comment by ahmedayman4a** [comment] 2020-04-08 14:48
@ayuu5h When you click show app the app is shown right?

**Comment by ayush5harma** [comment] 2020-04-08 14:48
> @ayuu5h When you click show app the app is shown right?

yes

**Comment by ahmedayman4a** [comment] 2020-04-08 14:54
> yes

This is the expected result and it is working.


So the problem is that when you click on 1Hack in this menu it doesn't open ,right?
![MacOS menu](https://user-images.githubusercontent.com/55313946/78798468-529aaa80-79b9-11ea-9fec-0fd9aa905ae4.png)
What is this menu called?

**Comment by ayush5harma** [comment] 2020-04-08 14:58
> > yes
> 
> This is the expected result and it is working.
> 
> So the problem is that when you click on 1Hack in this menu it doesn't open ,right?
> ![MacOS menu](https://user-images.githubusercontent.com/55313946/78798468-529aaa80-79b9-11ea-9fec-0fd9aa905ae4.png)
> What is this menu called?

Dock. Clicking on app icon in this  does initiate the app which is the usual behaviour, the problem is that the 1hack app initiates as minimised to the menu icon and not as overview and that's why picking app icon from dock won't show anything.

**Comment by ayush5harma** [comment] 2020-04-08 15:04
> > This is the expected result and it is working.
> > So the problem is that when you click on 1Hack in this menu it doesn't open ,right?
> > ![MacOS menu](https://user-images.githubusercontent.com/55313946/78798468-529aaa80-79b9-11ea-9fec-0fd9aa905ae4.png)
> > What is this menu called?
> 
> Dock. Clicking on app icon in this does initiate the app which is the usual behaviour, the problem is that the 1hack app initiates as minimised to the menu icon and not as overview and that's why picking app icon from dock won't show anything.
Check this @ahmedayman4a 
https://github.com/electron/electron/issues/7806

**Comment by ghost** [comment] 2020-04-08 16:20
> @rcsekar Can you post a gif showing the whole screen and you opening and closing 1Hack app(Don't crop any part of the screen out).
> Thank you.

https://gofile.io/?c=pK2qAk

**Comment by ayush5harma** [comment] 2020-04-08 16:55
> > @rcsekar Can you post a gif showing the whole screen and you opening and closing 1Hack app(Don't crop any part of the screen out).
> > Thank you.
> 
> https://gofile.io/?c=pK2qAk

Hey,redownload 1Hack-macos-x64-1.0.1.zip from the release section, u should get the menu icon as shown in the screenshot in previous comments.

**Closed as completed** 2020-04-17 19:59 UTC
Labels: bug, good first issue
